### ISSUE TITLE
Add glossary to the html page

### ISSUE THREAD

**Issue by naga8319** [naga8319/github-for-web-designers#1]
Hey Naga could  you please work on the glossary page. Thanks!

**Comment by naga8317** [comment]
Yeah sure thing! I will start working on it tonite..

**Comment by naga8319** [comment]
Great! I am closing the issue then...Thanks

**Comment by naga8317** [comment]
Could you please leave it open till I finish this issue ...Thanks

**Comment by naga8319** [comment]
Don't worry!! Everything will be alright
